insert into culture(id, name, description, period_Description, culture_Map, start_Year, end_Year) values (1,'Ancienne Egypte', 'L''Égypte antique est une ancienne civilisation du nord-est de l''Afrique, concentrée le long du cours inférieur du Nil, dans ce qui constitue aujourd''hui l''Égypte.', 'Du 4e millénaire au 1er siècle avant notre ère', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Ancient_Egypt_map-fr.svg/200px-Ancient_Egypt_map-fr.svg.png', -3150, -30);
insert into culture(id, name, description, period_Description, culture_Map, start_Year, end_Year) values (2,'Rome Antique', 'La Rome antique est à la fois la ville de Rome et l''État qu''elle fonde dans l''Antiquité. L''idée de Rome antique est inséparable de celle de la culture latine. Ce regroupement de villages au viiie siècle av. J.-C. parvint à dominer l''ensemble du monde méditerranéen et de l''Europe de l''Ouest du ier au ve siècle par la conquête militaire et par l''assimilation des élites locales. Sa domination a laissé d''importantes traces archéologiques et de nombreux témoignages littéraires. Elle façonne encore aujourd''hui l''image de la civilisation occidentale. Durant ces siècles, la civilisation romaine passe d''une monarchie à une république oligarchique puis à un empire autocratique.', 'VIIIe siècle ACN au Ve siècle PCN', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Carte_de_l%27Empire_romain_en_118_apr%C3%A8s_J.-C.jpg/220px-Carte_de_l%27Empire_romain_en_118_apr%C3%A8s_J.-C.jpg', -753, 476 );
insert into culture(id, name, description, period_Description, culture_Map, start_Year, end_Year) values (3,'Celte', 'Les Celtes ont constitué lors de la protohistoire européenne un groupe de populations1 indo-européennes parlant des langues celtiques et présentant une certaine unité culturelle2, bien que les interactions culturelles de l''Europe celtique ancienne demeurent incertaines et controversées3. Par ailleurs, la connaissance du processus de diffusion territoriale des anciennes populations celtiques reste à améliorer, en particulier quant à celles des Îles Britanniques et de la péninsule Ibérique', 'XIIe siècle ACN au Ier siècle ACN', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Hallstatt_LaTene.png/220px-Hallstatt_LaTene.png', -1350, -6);
insert into culture(id, name, description, period_Description, culture_Map, start_Year, end_Year) values (4,'Aztèqye', 'Les Aztèques, ou Mexicas (du nom de leur capitale, Mexico-Tenochtitlan), étaient un peuple amérindien du groupe nahua, c''est-à-dire de langue nahuatl.', 'XIIIe au XVIe siècle de notre ère', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Aztec_Empire_1519_map-fr.svg/langfr-280px-Aztec_Empire_1519_map-fr.svg.png', 1200, 1521);

insert into exposition (id, title, description, start_date, end_date, visitor_count, image_url) values (1,'I won Kadesh by a lot', 'Exposition sur la bataille de Kadesh et ses conséquences', '2020-11-25', '2021-02-25', 0 ,'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Ramses_II_at_Kadesh.jpg/260px-Ramses_II_at_Kadesh.jpg');

insert into artefact(identification, name, object_description, period_description, cultural_phase, type, material, localisation, imageurl, on_permanent_display, in_exposition, date_of_entry, start_year, end_year, culture_id, exposition_id)
values ('EG1000', 'Statue de Ramsès III', 'Statue en basalte de Ramsès III', 'Première moitié du XIIe siècle ACN', 'Nouvel Empire' , 'Statue', 'Pierre, Basalte', 'I won Kadesh by a lot', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Statue_of_Ramesses_III_-_Beth_Shean_-_1185-1153_BCE.jpeg/450px-Statue_of_Ramesses_III_-_Beth_Shean_-_1185-1153_BCE.jpeg', false, true, '1928-01-31', -1185, -1153, 1, 1);
insert into artefact(identification, name, object_description, period_description, cultural_phase, type, material, localisation, imageurl, on_permanent_display, in_exposition, date_of_entry, start_year, end_year, culture_id, exposition_id)
values ('CE1000', 'Casque d''Agris', 'Casque gaulois découvert en Charente en 1981', 'Second quart du IVe siècle ACN', 'Gaulois, La Tène', 'Armement', 'Métal, fer, bronze, or, argent et corail', 'Room 9', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Parade_helmet.jpg/220px-Parade_helmet.jpg', true, false, '1981-05-21', -375, -350, 3, null);
insert into artefact(identification, name, object_description, period_description, cultural_phase, type, material, localisation, imageurl, on_permanent_display, in_exposition, date_of_entry, start_year, end_year, culture_id, exposition_id)
values ('RE1000','Auguste de Prima Porta','Statue en marbre de l''Empereur Auguste','Ier siècle ACN au Ier siècle PCN','Empire Romain', 'Statue', 'Pierre, marbre de Paros', 'Room 27','https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Statue-Augustus.jpg/260px-Statue-Augustus.jpg',true, false,'1933-07-01',-20, 37,2,null);